import os

BOT_TOKEN = os.getenv('BOT_TOKEN')
OWNER_ID = os.getenv('OWNER_ID')
STORAGE_CHANNEL_ID = os.getenv('STORAGE_CHANNEL_ID')
FORCE_SUB_CHANNEL = os.getenv('FORCE_SUB_CHANNEL')
BOT_USERNAME = os.getenv('BOT_USERNAME')
